### ISSUE TITLE
Error while running fullsync

### ISSUE THREAD

**Issue by suchipa** [FredHutch/ad2openldap#4]
Might be linked to Issue#3
Output snippet of command `ad2openldap3 fullsync --dont-blame-ad2openldap -v`

```
INFO:ad2openldap3:line 54:ad2openldap - starting execution at 2017-11-29 23:38:59
WARNING:ad2openldap3:line 940:Help Desk in users but not in groups
WARNING:ad2openldap3:line 940:Schema Admins in users but not in groups
WARNING:ad2openldap3:line 940:Discovery Management in users but not in groups
WARNING:ad2openldap3:line 940:Customer Service in users but not in groups
WARNING:ad2openldap3:line 940:Enterprise Admins in users but not in groups
WARNING:ad2openldap3:line 940:Recipient Management in users but not in groups
WARNING:ad2openldap3:line 940:Server Management in users but not in groups
WARNING:ad2openldap3:line 940:Organization Management in users but not in groups
WARNING:ad2openldap3:line 940:Public Folder Management in users but not in groups
INFO:ad2openldap3:line 560:Successfully executed command: iptables -A INPUT -i eth0 -p tcp --dport 389 -j REJECT
INFO:ad2openldap3:line 560:Successfully executed command: /etc/init.d/slapd stop
INFO:ad2openldap3:line 555:A problem (1) has occurred calling slapadd -q -l /etc/ad2openldap/ldif/empty_ad2openldap.ldif
INFO:ad2openldap3:line 206:ad2openldap - finished execution at 2017-11-29 23:39:59
Traceback (most recent call last):
  File "/usr/local/bin/ad2openldap3", line 1123, in <module>
    sys.exit(main())
  File "/usr/local/bin/ad2openldap3", line 162, in main
    run_command(slapadd_dit_skeleton, verbose=arguments.verbose)
  File "/usr/local/bin/ad2openldap3", line 558, in run_command
    (return_code,command))
OSError: A problem (1) has occurred calling slapadd -q -l /etc/ad2openldap/ldif/empty_ad2openldap.ldif
```

output of command `slapadd -q -l /etc/ad2openldap/ldif/empty_ad2openldap.ldif`
```
slapadd: line 1: database #1 (dc=vm) not configured to hold "dc=local"; no database configured for that naming context
_###                   15.47% eta   none elapsed            none spd 579.4 k/s
Closing DB...
```

**Comment by jmkatcher** [comment]
It looks like there's something wrong with how openldap is itself configured.

As I remember, there's a base openldap initialization, on top of which a bare scheme is imported from empty_ad2openldap.ldif.

**Comment by suchipa** [comment]
It was linked to issue#3. I am able to run fullsync successfully, after a successful run of `rtcclean` command.
