### ISSUE TITLE
Unicode error for deltasync command

### ISSUE THREAD

**Issue by suchipa** [FredHutch/ad2openldap#5]
Similar to issue#3 getting unicode error for `ad2openldap3 deltasync --dont-blame-ad2openldap -v` command.

Output -
```
root@vagrant:/tmp# ad2openldap3 deltasync --dont-blame-ad2openldap -v
INFO:ad2openldap3:line 54:ad2openldap - starting execution at 2017-11-30 19:11:23
WARNING:ad2openldap3:line 942:Server Management in users but not in groups
WARNING:ad2openldap3:line 942:Customer Service in users but not in groups
WARNING:ad2openldap3:line 942:Public Folder Management in users but not in groups
WARNING:ad2openldap3:line 942:Schema Admins in users but not in groups
WARNING:ad2openldap3:line 942:Discovery Management in users but not in groups
WARNING:ad2openldap3:line 942:Enterprise Admins in users but not in groups
WARNING:ad2openldap3:line 942:Organization Management in users but not in groups
WARNING:ad2openldap3:line 942:Help Desk in users but not in groups
WARNING:ad2openldap3:line 942:Recipient Management in users but not in groups
INFO:ad2openldap3:line 206:ad2openldap - finished execution at 2017-11-30 19:12:15
Traceback (most recent call last):
  File "/usr/local/bin/ad2openldap3", line 1125, in <module>
    sys.exit(main())
  File "/usr/local/bin/ad2openldap3", line 168, in main
    ldif_diff(config)
  File "/usr/local/bin/ad2openldap3", line 1013, in ldif_diff
    old_ldif=parse_ldif(ad_export_previous)
  File "/usr/local/bin/ad2openldap3", line 1087, in parse_ldif
    ldict[ou][dn]=[compute_hash(entry),entry]
  File "/usr/local/bin/ad2openldap3", line 1051, in compute_hash
    m.update(part)
TypeError: Unicode-objects must be encoded before hashing
```

**Comment by jmkatcher** [comment]
Checked in probable (jinx!) fix.

**Comment by jmkatcher** [comment]
Thanks so much for your patience here.  Changed iteritems to items (no more in file) and ran til completion.

**Comment by suchipa** [comment]
I am able to run now successfully, closing the issue.
