### ISSUE TITLE
If number of OUs in AD change (increase or decrease) a full sync is attempted but fails 

### ISSUE THREAD

**Issue by bdconnolly** [FredHutch/ad2openldap#54]
If the number of OUs synced from AD change, then `ad2openldap3 deltasync ...` command attempts to perform a fullsync instead. This however fails with the following error message 

```
INFO:ad2openldap3:line 1124:Number of OUs is different.  old: dict_keys(['group', 'people', 'number3', 'number4']), new: dict_keys(['group', 'people', 'number4'])
INFO:ad2openldap3:line 205:Performing fullsync instead of deltasync
INFO:ad2openldap3:line 625:Successfully executed command: /sbin/iptables -A INPUT -i eth0 -p tcp --dport 389 -j REJECT
INFO:ad2openldap3:line 625:Successfully executed command: systemctl stop slapd
ERROR:ad2openldap3:line 284:Traceback (most recent call last):

  File "/usr/local/bin/ad2openldap3", line 219, in main
    run_command(slapadd_dit_skeleton, verbose=arguments.verbose)

  File "/usr/local/bin/ad2openldap3", line 612, in run_command
    stderr=subprocess.STDOUT)

  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)

  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)

FileNotFoundError: [Errno 2] No such file or directory: 'slapadd'

INFO:ad2openldap3:line 257:ad2openldap - finished execution at 2020-12-29 14:30:22
Traceback (most recent call last):
  File "/usr/local/bin/ad2openldap3", line 1233, in <module>
    sys.exit(main())
  File "/usr/local/bin/ad2openldap3", line 219, in main
    run_command(slapadd_dit_skeleton, verbose=arguments.verbose)
  File "/usr/local/bin/ad2openldap3", line 612, in run_command
    stderr=subprocess.STDOUT)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'slapadd'
```

At this point the LDAP server is down. The only way to fix the problem is to manually perform a `fullsync`

**Comment by jmkatcher** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'slapadd'


Something’s happened to the ’slapadd’ binary. Where did it go?
