### ISSUE TITLE
Intermittent issue (No such file or directory: 'ldapmodify')

### ISSUE THREAD

**Issue by suchipa** [FredHutch/ad2openldap#6]
When I am testing the cookbook in a vm(vagrant or EC2) this issue is happening intermittently while running delta sync. On checking found, `ldapmodify` is a command and looking for ldap-utils package. Even though, the ldap-utils is not installed, the deltasync works sometimes. Do I need to install ldap-utils?

I have pasted the error output as well as the success output when ldapmodify command is not available.

Error output -
```
root@ip-172-17-64-197:/var/log/ad2openldap# cat deltasync.log
INFO:ad2openldap3:line 54:ad2openldap - starting execution at 2017-12-06 15:15:01
WARNING:ad2openldap3:line 952:Recipient Management in users but not in groups
WARNING:ad2openldap3:line 952:Discovery Management in users but not in groups
WARNING:ad2openldap3:line 952:Customer Service in users but not in groups
WARNING:ad2openldap3:line 952:Enterprise Admins in users but not in groups
WARNING:ad2openldap3:line 952:Schema Admins in users but not in groups
WARNING:ad2openldap3:line 952:Organization Management in users but not in groups
WARNING:ad2openldap3:line 952:Help Desk in users but not in groups
WARNING:ad2openldap3:line 952:Server Management in users but not in groups
WARNING:ad2openldap3:line 952:Public Folder Management in users but not in groups
INFO:ad2openldap3:line 1114:/tmp/ad_export.ldif.0 has 16049 entries
INFO:ad2openldap3:line 1114:/tmp/ad_export.ldif has 16049 entries
INFO:ad2openldap3:line 1035:ad_export_previous -- ou: group, count: 8595
INFO:ad2openldap3:line 1035:ad_export_previous -- ou: people, count: 7446
INFO:ad2openldap3:line 1035:ad_export_previous -- ou: netgroup, count: 8
INFO:ad2openldap3:line 1043:ad_export_file -- ou: group, count: 8595
INFO:ad2openldap3:line 1055:Diffs 1
INFO:ad2openldap3:line 1043:ad_export_file -- ou: people, count: 7446
INFO:ad2openldap3:line 1043:ad_export_file -- ou: netgroup, count: 8
INFO:ad2openldap3:line 207:ad2openldap - finished execution at 2017-12-06 15:16:10
Traceback (most recent call last):
  File "/usr/local/bin/ad2openldap3", line 1135, in <module>
    sys.exit(main())
  File "/usr/local/bin/ad2openldap3", line 171, in main
    fatal=False)
  File "/usr/local/bin/ad2openldap3", line 557, in run_command
    stderr=subprocess.STDOUT)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'ldapmodify'
```

Success output -
```
root@vagrant:/var/log/ad2openldap# /usr/local/bin/ad2openldap3 deltasync --dont-blame-ad2openldap -v
INFO:ad2openldap3:line 54:ad2openldap - starting execution at 2017-12-06 15:48:55
WARNING:ad2openldap3:line 952:Server Management in users but not in groups
WARNING:ad2openldap3:line 952:Enterprise Admins in users but not in groups
WARNING:ad2openldap3:line 952:Recipient Management in users but not in groups
WARNING:ad2openldap3:line 952:Organization Management in users but not in groups
WARNING:ad2openldap3:line 952:Public Folder Management in users but not in groups
WARNING:ad2openldap3:line 952:Discovery Management in users but not in groups
WARNING:ad2openldap3:line 952:Customer Service in users but not in groups
WARNING:ad2openldap3:line 952:Schema Admins in users but not in groups
WARNING:ad2openldap3:line 952:Help Desk in users but not in groups
INFO:ad2openldap3:line 1114:/tmp/ad_export.ldif.0 has 16049 entries
INFO:ad2openldap3:line 1114:/tmp/ad_export.ldif has 16049 entries
INFO:ad2openldap3:line 1035:ad_export_previous -- ou: group, count: 8595
INFO:ad2openldap3:line 1035:ad_export_previous -- ou: netgroup, count: 8
INFO:ad2openldap3:line 1035:ad_export_previous -- ou: people, count: 7446
INFO:ad2openldap3:line 1043:ad_export_file -- ou: group, count: 8595
INFO:ad2openldap3:line 1043:ad_export_file -- ou: netgroup, count: 8
INFO:ad2openldap3:line 1043:ad_export_file -- ou: people, count: 7446
INFO:ad2openldap3:line 207:ad2openldap - finished execution at 2017-12-06 15:52:16
root@vagrant:/var/log/ad2openldap# ldapmodify
bash: ldapmodify: command not found
```

**Comment by jmkatcher** [comment]
Yes, please assume that ad2openldap requires ldap-utils.

I may have mentioned that 'deltasync' tries to be intelligent and if there is no usable diff file available (the difference between a previous LDAP state and now), it will go ahead and do a fullsync.   That's the case where it's not using 'ldapmodify'.  Usually though, proper deltasyncs are the correct mode of operation, using ldapmodify.

**Comment by jmkatcher** [comment]
Correction, my old version _tried_ to be intelligent but the current version is not.  If deltasync is specified, it will try to do deltasync or exit with a failure.

I'd like to try to reproduce how it can avoid ldapmodify being there and not error.

Still, please assume that ad2openldap requires ldap-utils as a prerequisite.

**Comment by jmkatcher** [comment]
Is ldapmodify not on that VM or is merely unreachable from your command line path?

**Comment by suchipa** [comment]
It was not there, after I installed ldap-utils, the command is available. But now I am getting below error. I don't know if its a real error.
```
root@vagrant:/tmp# cat /var/log/ad2openldap/deltasync.log
INFO:ad2openldap3:line 54:ad2openldap - starting execution at 2017-12-06 19:00:01
WARNING:ad2openldap3:line 952:Customer Service in users but not in groups
WARNING:ad2openldap3:line 952:Server Management in users but not in groups
WARNING:ad2openldap3:line 952:Recipient Management in users but not in groups
WARNING:ad2openldap3:line 952:Enterprise Admins in users but not in groups
WARNING:ad2openldap3:line 952:Organization Management in users but not in groups
WARNING:ad2openldap3:line 952:Help Desk in users but not in groups
WARNING:ad2openldap3:line 952:Schema Admins in users but not in groups
WARNING:ad2openldap3:line 952:Public Folder Management in users but not in groups
WARNING:ad2openldap3:line 952:Discovery Management in users but not in groups
INFO:ad2openldap3:line 1114:/tmp/ad_export.ldif.0 has 16049 entries
INFO:ad2openldap3:line 1114:/tmp/ad_export.ldif has 16049 entries
INFO:ad2openldap3:line 1035:ad_export_previous -- ou: group, count: 8595
INFO:ad2openldap3:line 1035:ad_export_previous -- ou: netgroup, count: 8
INFO:ad2openldap3:line 1035:ad_export_previous -- ou: people, count: 7446
INFO:ad2openldap3:line 1043:ad_export_file -- ou: group, count: 8595
INFO:ad2openldap3:line 1055:Diffs 1
INFO:ad2openldap3:line 1043:ad_export_file -- ou: netgroup, count: 8
INFO:ad2openldap3:line 1043:ad_export_file -- ou: people, count: 7446
INFO:ad2openldap3:line 565:A problem (32) has occurred calling ldapmodify -x -c -f /tmp/ad_export_delta.diff -D cn=admin,dc=local -w xxxxx -h localhost
INFO:ad2openldap3:line 207:ad2openldap - finished execution at 2017-12-06 19:04:15
```
Ooutput of command `ldapmodify -x -c -f /tmp/ad_export_delta.diff -D cn=admin,dc=local -w xxxxx -h localhost` 

```
deleting entry "cn=CS-R-Feng_Z_PERMUT~n-M,ou=group,dc=local"
ldap_delete: No such object (32)

adding new entry "cn=CS-R-Feng_Z_PERMUT~n-M,ou=group,dc=local"
ldap_add: No such object (32)
```

**Comment by jmkatcher** [comment]
That's fortunately not a "real" error and execution is properly proceeding.

There's an entry in Active Directory that can't be deleted or added to OpenLDAP.   I've seen this occasionally before and don't know what to do about it.  It apparently causes no problems.

Maybe I should bump this to Dirk for his opinion as it's more about AD than this tool...

**Comment by suchipa** [comment]
So do I need to run `fullsync` always and then `deltasync`. Will the presence of `ad_export.ldif` file would be check to run `fullsync`. Sometimes this file gets created even though `fullsync` didn't get executed successfully. I think `deltasync` is also recreating this file.

**Comment by jmkatcher** [comment]
Sadly, it seems like the current version seems to require fullsync to be initially run rather than deltasync, and deltasync afterward.  There's always 2 of these files, ad_export.ldif and (I think) ad_export.ldif.0 (the newer one is always renamed this on completion).  These are compared to generate the delta used for the actual update.

**Comment by jmkatcher** [comment]
P.S. I did mail Dirk re the error 32 object you reported.

**Comment by jmkatcher** [comment]
Closing as this is a combo of requiring ldap-utils and specific AD environmental nits
