### ISSUE TITLE
show stdout and stderr output of  slapadd command 

### ISSUE THREAD

**Issue by dirkpetersen** [FredHutch/ad2openldap#9]
d2openldap3 fullsync --dont-blame-ad2openldap -v

Traceback (most recent call last):
  File "/root/bin/ad2openldap3", line 1135, in <module>
    sys.exit(main())
  File "/root/bin/ad2openldap3", line 163, in main
    run_command(slapadd_ad_export_file, verbose=arguments.verbose)
  File "/root/bin/ad2openldap3", line 568, in run_command
    (return_code,command))
OSError: A problem (1) has occurred calling slapadd -q -l /tmp/ad_export.ldif

**Comment by jmkatcher** [comment]
Enabled this functionality if --verbose is selected - anything using run_command will output stdout/stderr to stdout for display/capture
